-- À exécuter une seule fois dans Supabase > SQL Editor.
-- Le site créera automatiquement la version de départ au premier chargement.

create table if not exists public.game_versions (
  id bigint generated by default as identity primary key,
  contributor text not null check (char_length(contributor) between 1 and 80),
  change_note text not null check (char_length(change_note) between 1 and 500),
  html_content text not null,
  created_at timestamptz not null default now()
);

alter table public.game_versions enable row level security;

-- Lecture publique : nécessaire pour que les collègues voient et testent l'historique.
drop policy if exists "Anyone can read game versions" on public.game_versions;
create policy "Anyone can read game versions"
on public.game_versions
for select
to anon, authenticated
using (true);

-- Ajout public : pratique pour un atelier interne accessible par lien.
-- Les anciennes versions ne peuvent PAS être modifiées ou supprimées depuis le site.
drop policy if exists "Anyone can add a game version" on public.game_versions;
create policy "Anyone can add a game version"
on public.game_versions
for insert
to anon, authenticated
with check (
  char_length(contributor) between 1 and 80
  and char_length(change_note) between 1 and 500
  and char_length(html_content) between 100 and 1500000
);

-- Aucun droit UPDATE ou DELETE n'est accordé.
-- L'historique reste donc immuable depuis l'interface publique.
